source 'https://github.com/CocoaPods/Specs.git'

target 'BDBorderedButton', :exclusive => true do
  pod "BDBorderedButton", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "BDBorderedButton", :path => "../"

  
end
